apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config-overlays
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://gitlab.consulting.redhat.com/evinel/openshift-toolkit-multicluster.git
      revision: main
      files:
        - path: "clusters/**/conf.yaml"
  template:
    metadata:
      name: "config-{{cluster.environment}}-{{cluster.name}}-overlay"
      labels:
        environment: "{{cluster.environment}}"
        cluster: "{{cluster.fqdn}}"
        region: "{{cluster.region}}"
        cloud: "{{cluster.cloud}}"
    spec:
      project: default
      source:
        repoURL: https://gitlab.consulting.redhat.com/evinel/openshift-toolkit-multicluster.git
        targetRevision: main
        path: clusters/{{cluster.environment}}/{{cluster.fqdn}}/overlay
      destination:
        server: "{{cluster.address}}"
      syncPolicy: {}
