apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-gitops-config
  namespace: openshift-gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: clusters/acm-hub.redhat.com
    repoURL: >-
      https://gitlab.consulting.redhat.com/evinel/openshift-toolkit-multicluster.git
    targetRevision: main
  syncPolicy: {}
